version: '3.9'

services:
  web:
    container_name: php-array_nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: php-array_php82
    image: php82
    build: .
    volumes:
      - ./app:/var/www/html
